#import "AlwaysOnOgg.h"
#include <assert.h>
static NSData *Page(NSData *packet,uint8_t flags,uint32_t seq,uint64_t gp){NSMutableData *d=[NSMutableData dataWithLength:28];uint8_t *b=d.mutableBytes;memcpy(b,"OggS",4);b[5]=flags;for(int i=0;i<8;i++)b[6+i]=gp>>(8*i);b[14]=7;for(int i=0;i<4;i++)b[18+i]=seq>>(8*i);b[26]=1;b[27]=packet.length;[d appendData:packet];b=d.mutableBytes;uint32_t c=0;for(NSUInteger i=0;i<d.length;i++){c^=(uint32_t)b[i]<<24;for(int j=0;j<8;j++)c=(c<<1)^((c&0x80000000)?0x04c11db7:0);}for(int i=0;i<4;i++)b[22+i]=c>>(8*i);return d;}
int main(int argc,const char **argv){@autoreleasepool{
    if(argc==3){NSURL *src=[NSURL fileURLWithPath:@(argv[1])],*dst=[NSURL fileURLWithPath:@(argv[2])];if(![NSFileManager.defaultManager copyItemAtURL:src toURL:dst error:nil])return 2;if(!TIOFinalizeAlwaysOnOgg(dst))return 3;puts("Validated Ogg export derivative ready; source unchanged.");return 0;}
    NSMutableData *head=[NSMutableData dataWithLength:19];uint8_t *h=head.mutableBytes;memcpy(h,"OpusHead",8);h[8]=1;h[9]=2;h[10]=56;h[11]=1;uint8_t toc[2]={0x18,0};NSData *audio=[NSData dataWithBytes:toc length:2];NSMutableData *file=[NSMutableData new];[file appendData:Page(head,2,0,0)];[file appendData:Page([@"OpusTags" dataUsingEncoding:NSUTF8StringEncoding],0,1,0)];[file appendData:Page(audio,4,2,1272)];
    NSURL *url=[[NSURL fileURLWithPath:NSTemporaryDirectory()] URLByAppendingPathComponent:NSUUID.UUID.UUIDString];assert([file writeToURL:url atomically:YES]);assert(TIOFinalizeAlwaysOnOgg(url));NSData *fixed=[NSData dataWithContentsOfURL:url];assert(![fixed isEqual:file]);assert(TIOFinalizeAlwaysOnOgg(url));assert([[NSData dataWithContentsOfURL:url] isEqual:fixed]);const uint8_t *b=fixed.bytes;NSUInteger offset=28+19+28+8;assert((b[offset+6]|(b[offset+7]<<8))==2880);assert(memcmp(b+offset+28,toc,2)==0);
    NSMutableData *corrupt=[fixed mutableCopy];((uint8_t *)corrupt.mutableBytes)[corrupt.length-1]^=1;assert([corrupt writeToURL:url atomically:YES]);assert(!TIOFinalizeAlwaysOnOgg(url));assert([[NSData dataWithContentsOfURL:url] isEqual:corrupt]);
    NSData *truncated=[file subdataWithRange:NSMakeRange(0,offset)];assert([truncated writeToURL:url atomically:YES]);assert(!TIOFinalizeAlwaysOnOgg(url));assert([NSFileManager.defaultManager removeItemAtURL:url error:nil]);puts("PASS: known 20ms granule repair, audio preservation, CRC validation, missing EOS refusal, idempotency.");
}return 0;}
