import Foundation

/// Generated by the state machine. Every provider callback and timer must carry this token.
public struct RoundToken: Hashable, Codable, Sendable {
    public let sessionID: UUID
    public let index: UInt64

    public init(sessionID: UUID, index: UInt64) {
        self.sessionID = sessionID
        self.index = index
    }
}

public enum ASRSource: String, Codable, Sendable { case local, cloud }

/// App policy, not an assertion about the official application's arbitration algorithm.
public enum ASRPolicy: String, Codable, Sendable {
    case localOnly, cloudOnly, preferCloudWithLocalFallback

    public func source(networkAvailable: Bool) -> ASRSource? {
        switch self {
        case .localOnly: return .local
        case .cloudOnly: return networkAvailable ? .cloud : nil
        case .preferCloudWithLocalFallback: return networkAvailable ? .cloud : .local
        }
    }
}

public enum NextRoundMode: String, Codable, Sendable { case manual, automatic }
public enum TTSMode: String, Codable, Sendable { case disabled, enabled }
public enum SessionPhase: String, Codable, Sendable {
    case disconnected, idle, listening, awaitingTranscript, generating, speaking, awaitingNextRound, awaitingToolApproval, closed
}
public enum SessionStage: String, Codable, Sendable, CaseIterable {
    case listening, recognition, model, speech, nextRound
}
public enum SessionExitReason: String, Codable, Sendable {
    case normal, timeout, serviceError, networkUnavailable, glassesExit, disconnected
}
public enum SessionFailure: String, Codable, Sendable {
    case unavailable, networkUnavailable, invalidAudio, emptyTranscript, textLimitExceeded, providerFailure, timedOut
}
public enum TTSStatus: Int, Codable, Sendable {
    case began = 1, paused = 2, resumed = 3, progress = 4, completed = 5
}

public struct SessionTimeouts: Equatable, Sendable {
    public let listeningSeconds: UInt32
    public let recognitionSeconds: UInt32
    public let modelSeconds: UInt32
    public let speechSeconds: UInt32
    public let nextRoundSeconds: UInt32

    /// Values are bounded to 1...600 seconds. The host must actually execute scheduled deadlines.
    public init(listeningSeconds: UInt32 = 30, recognitionSeconds: UInt32 = 8,
                modelSeconds: UInt32 = 60, speechSeconds: UInt32 = 90, nextRoundSeconds: UInt32 = 20) {
        self.listeningSeconds = min(600, max(1, listeningSeconds))
        self.recognitionSeconds = min(600, max(1, recognitionSeconds))
        self.modelSeconds = min(600, max(1, modelSeconds))
        self.speechSeconds = min(600, max(1, speechSeconds))
        self.nextRoundSeconds = min(600, max(1, nextRoundSeconds))
    }

    public func seconds(for stage: SessionStage) -> UInt32 {
        switch stage {
        case .listening: return listeningSeconds
        case .recognition: return recognitionSeconds
        case .model: return modelSeconds
        case .speech: return speechSeconds
        case .nextRound: return nextRoundSeconds
        }
    }
}

public struct VoiceSessionConfiguration: Equatable, Sendable {
    public let asrPolicy: ASRPolicy
    public let ttsMode: TTSMode
    public let nextRoundMode: NextRoundMode
    public let language: String
    public let maximumTextCharacters: Int
    public let maximumTextUTF8Bytes: Int
    public let maximumHistoryTurns: Int
    public let timeouts: SessionTimeouts

    /// Local ASR and text-only/manual rounds are privacy-preserving defaults; no provider is bundled.
    public init(asrPolicy: ASRPolicy = .localOnly, ttsMode: TTSMode = .disabled,
                nextRoundMode: NextRoundMode = .manual, language: String = "zh",
                maximumTextCharacters: Int = 16_384, maximumTextUTF8Bytes: Int = 65_536, maximumHistoryTurns: Int = 8,
                timeouts: SessionTimeouts = .init()) {
        self.asrPolicy = asrPolicy
        self.ttsMode = ttsMode
        self.nextRoundMode = nextRoundMode
        self.language = TextBounds.boundedPrefix(language, maximumCharacters: 64, maximumUTF8Bytes: 256)
        self.maximumTextCharacters = min(65_536, max(1, maximumTextCharacters))
        self.maximumTextUTF8Bytes = min(262_144, max(1, maximumTextUTF8Bytes))
        self.maximumHistoryTurns = min(32, max(0, maximumHistoryTurns))
        self.timeouts = timeouts
    }
}

public struct SessionSnapshot: Equatable, Sendable {
    public internal(set) var phase: SessionPhase = .disconnected
    public internal(set) var isConnected = false
    public internal(set) var networkAvailable = false
    public internal(set) var currentRound: RoundToken?
    public internal(set) var asrSource: ASRSource?
    public internal(set) var transcript = ""
    public internal(set) var response = ""
    public internal(set) var ttsStatus: TTSStatus?
    public internal(set) var lastExitReason: SessionExitReason?
    public internal(set) var lastFailure: SessionFailure?
    public internal(set) var completedRoundCount: UInt64 = 0
    public internal(set) var approvalSuspensionID: UUID?
}

public struct ASRTranscript: Equatable, Sendable {
    /// Monotonically increasing within a round; text is a complete snapshot, not an append delta.
    public let revision: UInt64
    public let text: String
    public let isFinal: Bool
    public init(revision: UInt64, text: String, isFinal: Bool) {
        self.revision = revision; self.text = text; self.isFinal = isFinal
    }
}

public struct ModelText: Equatable, Sendable {
    /// Complete text at this revision. Gaps are safe because no delta is lost.
    public let revision: UInt64
    public let text: String
    public init(revision: UInt64, text: String) { self.revision = revision; self.text = text }
}

public enum ConversationRole: String, Codable, Sendable { case user, assistant }
public struct ConversationMessage: Equatable, Codable, Sendable {
    public let role: ConversationRole
    public let text: String
    public init(role: ConversationRole, text: String) { self.role = role; self.text = text }
}

public enum AudioFormat: Equatable, Sendable {
    /// Headerless interleaved little-endian signed 16-bit PCM.
    case pcm16LE(sampleRate: Int, channels: Int)
    /// One already-identified encoded Opus packet, not an Ogg container.
    case opus(sampleRate: Int, channels: Int)
}

public struct AudioChunk: Equatable, Sendable {
    public let data: Data
    public let format: AudioFormat
    public init(data: Data, format: AudioFormat) { self.data = data; self.format = format }

    public var isValid: Bool {
        guard !data.isEmpty, data.count <= 65_536 else { return false }
        switch format {
        case let .pcm16LE(rate, channels):
            return (8_000...192_000).contains(rate) && (1...8).contains(channels)
                && data.count % (2 * channels) == 0
        case let .opus(rate, channels):
            return [8_000, 12_000, 16_000, 24_000, 48_000].contains(rate) && (1...2).contains(channels)
        }
    }
}

public enum VoiceSessionEvent: Sendable {
    case connected
    case disconnected
    case networkChanged(isAvailable: Bool)
    case wake
    case audioReceived(round: RoundToken, chunk: AudioChunk)
    case audioEnded(round: RoundToken)
    case asrResult(round: RoundToken, source: ASRSource, result: ASRTranscript)
    case modelText(round: RoundToken, update: ModelText)
    case modelFinished(round: RoundToken)
    case ttsStarted(round: RoundToken)
    case ttsPaused(round: RoundToken)
    case ttsResumed(round: RoundToken)
    case ttsProgress(round: RoundToken)
    case ttsInputFinished(round: RoundToken)
    /// Must denote final buffer drain after ttsInputFinished, not an interim empty queue.
    case ttsPlaybackDrained(round: RoundToken)
    case nextRound(round: RoundToken)
    case suspendForToolApproval(round: RoundToken, suspensionID: UUID)
    case finishToolApprovalSuspension(round: RoundToken, suspensionID: UUID)
    case interrupt(round: RoundToken)
    case glassesExited(round: RoundToken)
    case exitRequested(reason: SessionExitReason)
    case failed(round: RoundToken, stage: SessionStage, failure: SessionFailure)
    case timeout(round: RoundToken, stage: SessionStage)
}

public enum VoiceSessionEffect: Equatable, Sendable {
    case startRecognition(ASRRequest)
    case feedRecognition(round: RoundToken, chunk: AudioChunk)
    case finishRecognition(round: RoundToken)
    case cancelRecognition(round: RoundToken)
    case startCapture(round: RoundToken)
    case stopCapture(round: RoundToken)
    case requestModel(ModelRequest)
    case synthesizeAndPlay(SpeechRequest)
    /// Cancel local ASR/model/synthesis/player tasks. This is not a glasses packet.
    case cancelWork(round: RoundToken)
    case invalidateToolApprovals(round: RoundToken)
    case displayTranscript(round: RoundToken, text: String, isFinal: Bool)
    /// Semantic intent only: no verified arbitrary answer-text wire mapping is claimed.
    case displayResponse(round: RoundToken, text: String, isFinal: Bool)
    case reportTTSStatus(round: RoundToken, status: TTSStatus)
    /// A round completed. The transport adapter may map this to type 12, not type 7.
    case responseComplete(round: RoundToken)
    /// Request whole voice page/session exit; transport success is not device acknowledgement.
    case requestExit(round: RoundToken, reason: SessionExitReason)
    case scheduleTimeout(round: RoundToken, stage: SessionStage, seconds: UInt32)
    case cancelTimeout(round: RoundToken, stage: SessionStage)
    case reportFailure(round: RoundToken?, stage: SessionStage, failure: SessionFailure)

    /// Never apply a blanket current-token filter to all effects. Automatic continuation contains
    /// the OLD round's completion/cleanup followed by NEW round work in one ordered transition.
    public var executionPolicy: EffectExecutionPolicy {
        switch self {
        case .startRecognition, .feedRecognition, .finishRecognition, .startCapture, .requestModel,
             .synthesizeAndPlay, .scheduleTimeout:
            return .currentRoundWork
        case .cancelRecognition, .stopCapture, .cancelWork, .invalidateToolApprovals, .cancelTimeout:
            return .cleanup
        case .displayTranscript, .displayResponse, .reportTTSStatus, .responseComplete, .requestExit, .reportFailure:
            return .orderedOutput
        }
    }

    public var round: RoundToken? {
        switch self {
        case let .startRecognition(request): return request.round
        case let .requestModel(request): return request.round
        case let .synthesizeAndPlay(request): return request.round
        case let .feedRecognition(round, _), let .displayTranscript(round, _, _), let .displayResponse(round, _, _),
             let .reportTTSStatus(round, _), let .requestExit(round, _), let .scheduleTimeout(round, _, _),
             let .cancelTimeout(round, _): return round
        case let .finishRecognition(round), let .cancelRecognition(round), let .startCapture(round),
             let .stopCapture(round), let .cancelWork(round), let .invalidateToolApprovals(round),
             let .responseComplete(round): return round
        case let .reportFailure(round, _, _): return round
        }
    }
}

public enum EffectExecutionPolicy: String, Codable, Sendable {
    /// Revalidate its token immediately before starting deferred asynchronous work.
    case currentRoundWork
    /// Always apply in transition order, scoped to the effect's own round, even after a new round.
    case cleanup
    /// Preserve transition order; do not suppress the prior round's completion or final display.
    case orderedOutput
}

public struct VoiceSessionTransition: Equatable, Sendable {
    public let snapshot: SessionSnapshot
    public let effects: [VoiceSessionEffect]
    public init(snapshot: SessionSnapshot, effects: [VoiceSessionEffect]) {
        self.snapshot = snapshot; self.effects = effects
    }
}
